### ISSUE TITLE
Twitter Bot does not work anymore

### ISSUE THREAD

**Issue by mcanducci** [social-manager-tools/twitter-bot.js#10]
### Versions

SMT 0.5.4
Twitter Bot 0.2.4

- **Operating System:** Mac Os X Mojave
- **Browser:** Google Chrome Versione 69.0.3497.100 (Build ufficiale) (a 64 bit)

### Expected Behavior

Please describe the program's expected behavior.

It should run :-)

### Actual Behavior

After pressing the START button and moving to LOGS window, you can see that everything stops after these four lines: 

[WARNING] Bot work? Please donate for support this project!
[WARNING] Donate with patreon: http://patreon.ptkdev.io
[WARNING] Donate with paypal: http://paypal.ptkdev.io
[INFO] Bot is updated! :D

### Steps to Reproduce

1. feel the form fields
2. run bot
3. press logs button

**Comment by ptkdev** [comment]
<a href="http://patreon.ptkdev.io" alt="Patreon Backer"><img src="https://img.shields.io/badge/donate-patreon-F87668.svg"></a> <a href="http://paypal.ptkdev.io" alt="Paypale Donate"><img src="https://img.shields.io/badge/donate-paypal-46AFE0.svg"></a>  <a href="http://coffee.ptkdev.io" alt="Ko-fi Donate"><img src="https://img.shields.io/badge/buy%20me-coffee-4B788C.svg"></a>
